controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint_F2
      - arm_joint_F3
      - arm_joint_F4
      - arm_joint_F5
      - arm_joint_F6
      - arm_joint_F8
initial:  # Define initial robot poses.
  - group: arm
    pose: home