# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint_F2
    - arm_joint_F3
    - arm_joint_F4
    - arm_joint_F5
    - arm_joint_F6
    - arm_joint_F8
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_joint_F2
      - arm_joint_F3
      - arm_joint_F4
      - arm_joint_F5
      - arm_joint_F6
      - arm_joint_F8

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint_F2
    - arm_joint_F3
    - arm_joint_F4
    - arm_joint_F5
    - arm_joint_F6
    - arm_joint_F8
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_joint_F2: {trajectory: 0.1, goal: 0.1}
      arm_joint_F3 : {trajectory: 0.1, goal: 0.1}
      arm_joint_F4: {trajectory: 0.1, goal: 0.1}
      arm_joint_F5: {trajectory: 0.1, goal: 0.1}
      arm_joint_F6: {trajectory: 0.1, goal: 0.1}
      arm_joint_F8: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1

/gazebo_ros_control/pid_gains:
  arm_joint_F2: {p: 1000.0, i: 0.0, d: 0.1}
  arm_joint_F3: {p: 1000.0, i: 0.0, d: 0.1}
  arm_joint_F4: {p: 1000.0, i: 0.0, d: 0.1}
  arm_joint_F5: {p: 1000.0, i: 0.0, d: 0.1}
  arm_joint_F6: {p: 1000.0, i: 0.0, d: 0.1}
  arm_joint_F8: {p: 1000.0, i: 0.0, d: 0.1}

